return {
  "mason-org/mason.nvim",
  opts = {
    ensure_installed = {
      "bash-language-server",
      "black",
      "css-lsp",
      "clangd",
      "dockerfile-language-server",
      "hadolint",
      "html-lsp",
      "emmet-ls",
      "typescript-language-server",
      "json-lsp",
      "lua-language-server",
      "markdown-toc",
      "markdownlint",
      "markdownlint-cli2",
      "marksman",
      "phpactor",
      "prettier",
      "pyright",
      "ruff",
      "shellcheck",
      "shfmt",
      "sqlfluff",
      "stylua",
      "tailwindcss-language-server",
      "taplo",
      "vim-language-server",
      "yaml-language-server",
      "omnisharp",
    },
  },
}
